import api, { asList, unwrap } from './api';
export const getComplaints = async (params = {}) => asList(unwrap(await api.get('/complaints', { params })));
export const getMyComplaints = async () => asList(unwrap(await api.get('/complaints/my')));
export const getComplaint = async (id) => unwrap(await api.get(`/complaints/${id}`), 'complaint');
export const createComplaint = async (payload) => unwrap(await api.post('/complaints', payload), 'complaint');
export const updateComplaint = async (id, payload) => unwrap(await api.put(`/complaints/${id}`, payload), 'complaint');
export const deleteComplaint = async (id) => unwrap(await api.delete(`/complaints/${id}`));
export const upvoteComplaint = async (id) => unwrap(await api.post(`/complaints/${id}/upvote`), 'complaint');
export const updateComplaintStatus = async (id, status) => unwrap(await api.put(`/complaints/${id}/status`, { status }), 'complaint');
export const assignComplaint = async (id, payload) => unwrap(await api.put(`/complaints/${id}/assign`, payload), 'complaint');
